## Numpy Array Operations

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

## Basic slicing
print("Basic slicing: ", arr[2:7])

## step slicing
print("Step Slicing: ", arr[2:8:2])

Basic slicing:  [3 4 5 6 7]
Step Slicing:  [3 5 7]


In [6]:
arr_2d = [[1,2,3], [4,5,6]]

# print(arr_2d[1,2]) # not allowed on Python List

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[1]) # [4,5,6]
print("Entire Column: ", arr_2d[:, 1]) # [2,5,8]

Specific Element:  6
Entire row:  [4 5 6]
Entire Column:  [2 5 8]


## Sorting

In [7]:
unsorted = np.array([5,3,7,2,8,0,1,2])
print("Sorted array : ", np.sort(unsorted))

unsorted_2d = np.array([[2,1], 
                        [4,3], 
                        [2,5]])
print("Sorted 2d array by column: \n", np.sort(unsorted_2d, axis=0))
print("Sorted 2d array by row: \n", np.sort(unsorted_2d, axis=1))

Sorted array :  [0 1 2 2 3 5 7 8]
Sorted 2d array by column: 
 [[2 1]
 [2 3]
 [4 5]]
Sorted 2d array by row: 
 [[1 2]
 [3 4]
 [2 5]]


## Filter

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


### Filter with mask

In [9]:
mask = numbers > 5
print("Mask: ", mask)
print("Numbers greater than 5: ", numbers[mask])

Mask:  [False False False False False  True  True  True  True  True]
Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing and np.where()

In [10]:
indeces = [0,4,5]
print("Array with indeces: ", numbers[indeces])

where_result = np.where(numbers > 5)
print("Where result: ", where_result) # returns tuple of arrays
print("Numbers greater than 5 with Np where: ", numbers[where_result])


Array with indeces:  [1 5 6]
Where result:  (array([5, 6, 7, 8, 9]),)
Numbers greater than 5 with Np where:  [ 6  7  8  9 10]


In [11]:
condition_arr = np.where(numbers > 5, numbers * 4, numbers)
print("Condition array: ", condition_arr)

condition_arr = np.where(numbers > 5, numbers * 4, numbers * 2)
print("Condition array: ", condition_arr)

Condition array:  [ 1  2  3  4  5 24 28 32 36 40]
Condition array:  [ 2  4  6  8 10 24 28 32 36 40]


## Adding and Removing data

In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

merged = np.concatenate((arr1, arr2))
print("Merged array: ", merged)

Merged array:  [1 2 3 4 5 6]


### Adding row and column

In [19]:
arr = np.array([[1,2,3],
                [4,5,6]])

new_row = np.array([[7,8,9]])
with_new_row = np.vstack((arr, new_row))
print("Array with new row: \n", with_new_row)

new_col = np.array([[10], [11]])
with_new_col = np.hstack((arr, new_col))
print("Array with new column: \n", with_new_col)

Array with new row: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with new column: 
 [[ 1  2  3 10]
 [ 4  5  6 11]]


### delete element

In [20]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2) # delete index 2
print("Deleted array: ", deleted) # [1,2,4,5,6]

Deleted array:  [1 2 4 5 6]
