## Learn About Numpy

In [1]:
import numpy as np

In [4]:
arr_1d = np.array([1,2,3,4,5])

print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])

print("2D array:\n", arr_2d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### Python List vs Numpy Array

In [ ]:
py_list = [1,2,3]

print("Multiplication of list by 2:", py_list *2) # This will repeat the list, not multiply each element by 2

np_array = np.array([1,2,3])

print("Multiplication of numpy array by 2:", np_array * 2) # This will multiply each element by 2

Multiplication of list by 2: [1, 2, 3, 1, 2, 3]
Multiplication of numpy array by 2: [2 4 6]


In [43]:
import time

start_time = time.time()
py_list = [i for i in range(1000000)]
end_time = time.time()

print("Time taken to create python list:", end_time - start_time)


start_time = time.time()
np_array = np.arange(1000000)
end_time = time.time()

print("Time taken to create numpy array:", end_time - start_time)

Time taken to create python list: 0.06556558609008789
Time taken to create numpy array: 0.001993894577026367


###  Creating Array

In [ ]:
zeros = np.zeros((3,4))
print("Zeros array:\n", zeros)

ones = np.ones((3,4))
print("Ones array:\n", ones)

full = np.full((2,3), 7)
print("Full array:\n", full)

random = np.random.random((2,3))
print("Random array:\n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array:", sequence)



Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array:
 [[7 7 7]
 [7 7 7]]
Random array:
 [[0.05308001 0.66233224 0.36124797]
 [0.91998816 0.34704001 0.22479411]]
Sequence array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


### Vector, Matrix and Tensor

In [ ]:
## 1D array
vector = np.array([1, 2, 3])
print("Vector: ", vector)

## 2D array
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:\n", matrix)

## More than 2D array (tensor)
tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor:\n", tensor)

Vector:  [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [53]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data type: ", arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
Data type:  int64


### Array Reshaping

In [5]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape(3,4)
print("Reshaped array: \n", reshaped)


## It flat array and returns copy
flattened = reshaped.flatten()
print("Flattened array: ", flattened)

## It flat array and return original array
ravelled = reshaped.ravel()
print("Ravelled array: ", ravelled)
print("Reshaped array: \n", reshaped)

## Transpose
transpose = reshaped.T
print("Transpose array: \n", transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
